#PlayerAbilityLib configuration file
#
#If alwaysLogTamperWarnings is set to false, external update messages will be logged only once per game session
#Wed Apr 15 04:46:34 UTC 2026
alwaysLogTamperWarnings=true
